{
  "ibwells-0010-001-06" : {
    "title" : [ "Ida B. Wells-Barnett her children, Charles Aked; Ida B. Wells, Jr.; Alfreda Marguerita; and, Herman Kohlsaat.." ],
    "creator" : [ "unknown" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "Barnett, Charles Aked, born 1896", "Barnett, Herman Kohlsaat, 1897-1975", "Barnett, Ida B. Wells, 1901-1988", "Duster, Alfreda Barnett, 1904-1983", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "1909" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-001-06" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Children of Ida B. Wells-Barnett (standing), activist, journalist, teacher, and anti-lynching leader, and lawyer Ferdinand Lee Barnett, publisher of The Conservator, the first African American newspaper in Chicago. From left: Charles Aked; Ida B. Wells, Jr.; Alfreda Marguerita; and, Herman Kohlsaat." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-001-06.pdf"
  },
  "ibwells-0008-010-02" : {
    "title" : [ "\"Never Allowed to be Dear,\" The Chicago Times, Sunday, September 3, 1893" ],
    "creator" : [ "Chicago Times" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Newspapers" ],
    "date" : [ "1893-08-03" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-010-02.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Page from the Chicago Times including the article \"Never Allowed to be Dear,\" quoting Ida B. Wells on economic inequality in the South. Photocopy." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-010-02.pdf"
  },
  "ibwells-0010-001-07" : {
    "title" : [ "Postcard featuring photograph of Ida B. Wells, circa 1910" ],
    "creator" : [ "unknown" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic postcards" ],
    "date" : [ "circa 1910" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-001-07" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Ida B. Wells-Barnett, activist, journalist, teacher, and anti-lynching leader." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-001-07.pdf"
  },
  "ibwells-0010-001-05" : {
    "title" : [ "Ferdinand Lee Barnett" ],
    "creator" : [ "unknown" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "Barnett, Ferdinand Lee, 1852-1936", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "1906/1908" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-001-05" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Lawyer Ferdinand Lee Barnett, publisher of The Conservator, the first African American newspaper in Chicago. Barnett married Ida B. Wells, activist, journalist, teacher, and anti-lynching leader in 1895." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-001-05.pdf"
  },
  "ibwells-0008-010-14" : {
    "title" : [ "\"Mrs. Ida Barnett, Colored Leader, 62, Dies Suddenly,\" The Chicago Tribune, March 25, 1931" ],
    "creator" : [ "Chicago Tribune" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text", "Newspapers" ],
    "format" : [ ],
    "date" : [ "1931-03-25" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-010-14.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Mrs. Ida Barnett, Colored Leader, 62, Dies Suddenly,\" The Chicago Tribune, March 25, 1931, Obituary for Ida B. Wells. Typescript.." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-010-14.pdf"
  },
  "ibwells-0008-009-09" : {
    "title" : [ "Letter, Ida B. Wells to daughters Ida and Alfreda, October 30, 1920" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Letters", "Manuscripts" ],
    "date" : [ "1920-10-30" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-009-09.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Handwritten letter from Ida B. Wells to her daughters Ida and Alfreda." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-009-09.pdf"
  },
  "ibwells-0008-009-08" : {
    "title" : [ "\"To the Young Men Who Want to Go to France,\" flyer, with letter on verso, circa 1910-1920" ],
    "creator" : [ "McCormick, William" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Flyers", "Letters" ],
    "date" : [ "circa 1910-1920" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-009-08.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "\"To the Young Men Who Want to Go to France,\" original flyer, undated [ca. 1910-1920], with handwritten letter on verso from \"Wm. McCormick\" to Ida B. Wells, concerning \"Levena Sharp,\" a pregnant 17-year old rooming with \"Mrs. Wm. Dorsey.\"" ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-009-08.pdf"
  },
  "ibwells-0008-010-01" : {
    "title" : [ "Article which appeared in The Ladies Pictorial, England, May 1893" ],
    "creator" : [ "Ladies Pictorial" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Manuscripts", "Newspapers" ],
    "date" : [ "1893-05" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-010-01.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Typescript text of an article from The Ladies Pictorial describing Ida B. Wells 1893 speaking tour in England. 1p." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-010-01.pdf"
  },
  "ibwells-0010-001-10" : {
    "title" : [ "Ida B. Wells-Barnett." ],
    "creator" : [ "unknown" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "circa 1920" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-001-10" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Ida B. Wells-Barnett, activist, journalist, teacher, and anti-lynching leader." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-001-10.pdf"
  },
  "ibwells-0010-001-04" : {
    "title" : [ "Ida B. Wells-Barnett with son, Charles Aked Barnett" ],
    "creator" : [ "Johnson, J. Scott" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "Barnett, Charles Aked, born 1896", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "1896-11" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-001-04" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Ida B. Wells-Barnett, activist, journalist, teacher, and anti-lynching leader, with her first-born son, Charles Aked Barnett." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-001-04.pdf"
  },
  "ibwells-0010-008" : {
    "title" : [ "Scrapbook documenting the life of Ferdinand Barnett." ],
    "creator" : [ "Barnett, Ferdinand Lee, 1852-1936" ],
    "subject" : [ "Barnett, Ferdinand Lee, 1852-1936", "Wells-Barnett, Ida B., 1862-1931" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Scrapbooks" ],
    "date" : [ "undated" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0010-008.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Scrapbook documenting the life of lawyer and journalist Lawyer Ferdinand Lee Barnett, publisher of The Conservator, the first African American newspaper in Chicago, and husband of civil rights leader Ida B. Wells. Photocopy." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-008.pdf"
  },
  "ibwells-0008-010-11" : {
    "title" : [ "\"Miss Ida B. Wells,\" excerpt from \"The College of Life or Practical Self-Educator,\" 1895" ],
    "creator" : [ "Northrup, Henry Davenport, 1836-1909" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ ],
    "date" : [ "undated" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-010-11.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "\"Miss Ida B. Wells,\" typescript excerpt from Henry Davenport Northrop, Joseph R. Gay, and I. Garland Penn, \"The college of life, or, Practical self-educator : a manual of self-improvement for the colored race : forming an educational emancipator and a guide to success : giving examples and achievements of successful men and women of the race as an incentive and inspiration to the rising generation : including Afro-American progress illustrated : the whole embracing business, social, domestic, historical and religious education, 1895." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-010-11.pdf"
  },
  "ibwells-0001-001-008" : {
    "title" : [ "Crusade for Justice, original manuscript" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Manuscripts" ],
    "date" : [ "circa 1926" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0001-001-008.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Original manuscript of Crusade for Justice: the Autobiography of Ida B. Wells, in Wells' own hand. Preface, two versions, (5 p.); Chapters I through VI, (30 p.), Chapters VII through XVI (42 p.); \"Shipmates on first voyage to England... Chapter 5 of my first writing\" in pencil; newspaper clippings." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0001-001-008.pdf"
  },
  "ibwells-0010-001-01" : {
    "title" : [ "Ida B. Wells, standing left, with Maurine Moss, widow of Tom Moss, lynched in Memphis March 9, 1892, with Tom Moss Jr. " ],
    "creator" : [ "Griffin, W. F." ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "Milliken, Elizabeth Cooper Moss, 1862-1910", "Browning, Maurine Moss, 1891-1971", "Moss, Thomas Henry, 1892-1906", "Moss, Thomas Henry, died 1892 ", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "circa 1894" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-001-01" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "\tIda B. Wells-Barnett (left), activist, journalist, teacher, and anti-lynching leader. She is pictured with the family of Thomas H. Moss, Sr., Maurine, Betty, and Thomas, Jr. Mr. Moss, a postman and grocery store owner, was lynched in Memphis, Tennessee, 9 March 1892. The photograph was taken in Indianapolis, Indiana where his wife and children had relocated after the murder." ],
    "spatial" : [ "Indianapolis, Indiana" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-001-01.pdf"
  },
  "ibwells-0010-001-03" : {
    "title" : [ "Ida B. Wells, photograph of engraved illustration." ],
    "creator" : [ "Griffin, W. F." ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "1891" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-001-03" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "IEngraving (photograph copy) of Ida B. Wells-Barnett, activist, journalist, teacher, and anti-lynching leader, printed in the 1891 edition of Irvine G. Penn's \"The Afro-American press and its editors.\"" ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-001-03.pdf"
  },
  "ibwells-0008-010-12" : {
    "title" : [ "Excerpt from \"The White Side of a Black Subject,\"  1897" ],
    "creator" : [ "Wood, Norman Barton, 1857-1933" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ ],
    "date" : [ "undated" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-010-12.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Typescript excerpt from Rev. Norman B. Wood, \"The White Side of a Black Subject,\" Chicago: American Publishing House, 1897, supporting Wells' anti-lynching campaign." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-010-12.pdf"
  },
  "ibwells-0009-008" : {
    "title" : [ "Ida B. Wells pocket diary, 1885-1887" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Diaries" ],
    "date" : [ "1885-1887" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0009-008.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Ida B. Wells' diary, 1885-1887. Entries begin in Holly Springs, Mississippi, December 29, 1885, and end in Woodstock, Tennessee, September 12, 1887." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0009-008.pdf"
  },
  "ibwells-0008-010-13" : {
    "title" : [ "Mrs. Delores Johnson Farrow, \"Side Lights or Shadows on the Recent Race Riots at East St. Louis, Illinois,\" The Broad Ax, Chicago, July 28, 1917" ],
    "creator" : [ "Farrow, Delores Johnson" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text", "Newspapers" ],
    "format" : [ ],
    "date" : [ "1917-07-28" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-010-13.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Mrs. Delores Johnson Farrow, \"Side Lights or Shadows on the Recent Race Riots at East St. Louis, Illinois,\" The Broad Ax, Chicago, July 28, 1917, on Farrow's trip to East St. Louis with Ida B. Wells. Photocopy." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-010-13.pdf"
  },
  "ibwells-0010-001-02" : {
    "title" : [ "Ida B. Wells, portrait photograph" ],
    "creator" : [ "Cihak and Zimz" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ " circa 1893-1894" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-001-02" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Ida B. Wells-Barnett, activist, journalist, teacher, and anti-lynching leader, mounted portrait photograph." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-001-02.pdf"
  },
  "ibwells-0010-002-20" : {
    "title" : [ "Ida B. Wells-Barnett, 1920" ],
    "creator" : [ "unknown" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "1920-06-06" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-002-20" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Ida B. Wells-Barnett, activist, journalist, teacher, and anti-lynching leader." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-002-20.pdf"
  },
  "ibwells-0008-008-01" : {
    "title" : [ "\"Marriage Bells,\" The New York Age, November 1892" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Newspapers" ],
    "date" : [ "1892-11" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-008-01.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Article announcing the upcoming marriage of Marinda Cooper to Dr. J. B. Elbert, and recounting the March 1892 lynchings and racist attacks that drove the couple, their families, and the articles author to leave Memphis, Tennessee. Written by Ida B. Wells under the penname \"Iola.\" Photocopy." ],
    "spatial" : [ "New York, New York" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-008-01.pdf"
  },
  "ibwells-0008-0012" : {
    "title" : [ "Ida B. Wells Woman's Club" ],
    "creator" : [ "Ida B. Wells Woman's Club" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text", "Newspapers" ],
    "format" : [ ],
    "date" : [ "1940s-1960s" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-0012.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/UND/1.0/" ],
    "description" : [ "Ephemera from the Ida B. Wells Woman's Club: Membership forms, invitations, brochures, newsclippings." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-0012.pdf"
  },
  "ibwells-0008-008-02" : {
    "title" : [ "\"Lynch Law in All its Phases\"" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Books" ],
    "date" : [ "1893-02-13" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-008-02.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Text of an address given by Ida B. Wells at Tremont Temple in the Monday Lectureship. Photocopy." ],
    "spatial" : [ "Boston, Massachusetts" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-008-02.pdf"
  },
  "ibwells-0008-008-03" : {
    "title" : [ "\"The Reign of Mob Law: Iola’s Opinion of Doings in the Southern Field,\" New York Age, February 18, 1893, combined with \"The Lynchers Wince,\" New York Age, September 19, 1891" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Newspapers", "Manuscripts" ],
    "date" : [ "1891-09-08", "1893-02-18" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-008-03.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Typescript and hand-written texts of two editorials written by Ida B. Wells under the penname \"Iola.\" The articles, written for the African-American newspaper the New York Age, document lynchings and community self-defense in southern states." ],
    "spatial" : [ "New York, New York" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-008-03.pdf"
  },
  "ibwells-0010-002-19" : {
    "title" : [ "Ida B. Wells-Barnett, circa 1920" ],
    "creator" : [ "unknown" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "circa 1920" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-002-19" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Ida B. Wells-Barnett, activist, journalist, teacher, and anti-lynching leader." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-002-19.pdf"
  },
  "ibwells-0008-008-04" : {
    "title" : [ "\"Lynch Law in the United States: to the Editor of the Daily Post,\" Birmingham Daily Post, May 14, 1894, with annotations by Ida B. Wells." ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Newspapers", "Manuscripts" ],
    "date" : [ "189-05-16" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-008-04.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Letter to the Editor of the Birmingham [England] Daily Post, written by Ida B. Wells in response to an editorial protesting upcoming meetings in Birmingham addressing lynchings in the United States. Includes handwritten annotations by Ida B. Wells.  Photocopy." ],
    "spatial" : [ "Birmingham, England" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-008-04.pdf"
  },
  "ibwells-0008-008-05" : {
    "title" : [ "\"How Enfranchisement Stops Lynching,\" Original Rights Magazine, vol. I, no. 4 (June 1910)" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Periodicals" ],
    "date" : [ "1910-06" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-008-05.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Article written by Ida B. Wells for Original Rights Magazine. Includes cover, table of contents, pages 42-53. Photocopy." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ "English" ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-008-05.pdf"
  },
  "ibwells-0010-002-18" : {
    "title" : [ "Ida B. Wells-Barnett with her sisters, 1920" ],
    "creator" : [ "Woodard Studio" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "1920" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-002-18" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Ida B. Wells-Barnett (center), activist, journalist, teacher, and anti-lynching leader, with her sisters." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-002-18.pdf"
  },
  "ibwells-0010-002-15" : {
    "title" : [ "Ida B. Wells-Barnett, with husband, Ferdinand, and daughter, Alfreda, 1919" ],
    "creator" : [ "unknown" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "Barnett, Ferdinand Lee, 1852-1936", "Duster, Alfreda Barnett, 1904-1983", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "1919-08" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-002-15" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Lawyer Ferdinand Lee Barnett (seated), publisher of The Conservator, the first African American newspaper in Chicago, and his wife Ida B. Wells-Barnett (left), activist, journalist, teacher, and anti-lynching leader. They are pictured with their daughter Alfreda (right), and son Herman (in window) in the backyard of their Chicago home at 3624 Grand Boulevard." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-002-15.pdf"
  },
  "ibwells-0008-011-01" : {
    "title" : [ "\"A Darky Damsel Obtains a Verdict for Damages Against the Chesapeake & Ohio Railroad,\" Memphis Appeal-Avalanche, December 25, 1884" ],
    "creator" : [ "Memphis Appeal-Avalanche" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text", "Newspapers" ],
    "format" : [ ],
    "date" : [ "1931-12-25" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-011-01.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "\"A Darky Damsel Obtains a Verdict for Damages Against the Chesapeake & Ohio Railroad,\" Memphis Appeal-Avalanche, December 25, 1884 Typescript." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-011-01.pdf"
  },
  "ibwells-0010-002-14" : {
    "title" : [ "Ferdinand L. Barnett with daughter, Alfreda, 1919" ],
    "creator" : [ "unknown" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "Barnett, Ferdinand Lee, 1852-1936", "Duster, Alfreda Barnett, 1904-1983", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "1919-08" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-002-14" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Alfreda M. Barnett (left), daughter of lawyer Ferdinand Lee Barnett (right), publisher of The Conservator, the first African American newspaper in Chicago, and Ida B. Wells-Barnett, activist, journalist, teacher, and anti-lynching leader. They are pictured in the backyard of their Chicago home at 3624 Grand Boulevard." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-002-14.pdf"
  },
  "ibwells-0010-002-16" : {
    "title" : [ "Ferdinand L. Barnett, with son, Herman K. Barnett in window in background, 1919" ],
    "creator" : [ "unknown" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "Barnett, Ferdinand Lee, 1852-1936", "Barnett, Herman Kohlsaat, 1897-1975", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "1919-08" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-002-16" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Lawyer Ferdinand Lee Barnett (seated), publisher of The Conservator, the first African American newspaper in Chicago, and his son Herman (in window). They are pictured in the backyard of their Chicago home at 3624 Grand Boulevard." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-002-16.pdf"
  },
  "ibwells-0008-011-02" : {
    "title" : [ "Excerpts from \"Cases Argued and Determined in the Supreme Court of Tennessee,\" Shelby County, April Term, 1887" ],
    "creator" : [ ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ ],
    "date" : [ "1887" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-011-02.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "\"Cases Argued and Determined in the Supreme Court of Tennessee,\" Shelby County, April Term, 1887: 613-615, 631, regarding appeal and overturn of Railroad v. Wells case. Photocopy and typescript" ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-011-02.pdf"
  },
  "ibwells-0010-002-17" : {
    "title" : [ "Ida B. Wells-Barnett, flanked by daughter, Alfreda and daughter-in-law Fiona Davis-Barnett, 1919" ],
    "creator" : [ "unknown" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "Duster, Alfreda Barnett, 1904-1983", "Barnett, Fiona Davis", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "1919-08" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-002-17" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Ida B. Wells-Barnett (center), activist, journalist, teacher, and anti-lynching leader. She is pictured with her daughter Alfreda (left), and daughter-in-law Fiona Davis Barnett (wife of Herman, right) in the backyard of the Barnett's Chicago home at 3624 Grand Boulevard." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-002-17.pdf"
  },
  "ibwells-0010-002-13" : {
    "title" : [ "Ida B. Wells-Barnett with nephew Jack Calvert Wells, 1919." ],
    "creator" : [ "unknown" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "Wells, Jack Calvert", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "1919-08" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-002-13" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Ida B. Wells-Barnett, activist, journalist, teacher, and anti-lynching leader. She is pictured with her nephew Jack Calvert Wells in the backyard of her Chicago home at 3624 Grand Boulevard." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-002-13.pdf"
  },
  "ibwells-0010-002-12" : {
    "title" : [ "Ida B. Wells-Barnett, wearing \"Martyred Negro Soldiers\" button, circa 1917-1919" ],
    "creator" : [ "Webb Studio" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American soldiers", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "1917/1919" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-002-12" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Ida B. Wells-Barnett, activist, journalist, teacher, and anti-lynching leader. She is pictured wearing a button she created to publicize a memorial service for African American combatants court-martialed and hanged in Houston, Texas in the summer of 1917. The button's text reads \"In Memoriam Martyred Negro Soldiers Dec. 11, 1917." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-002-12.pdf"
  },
  "ibwells-0010-002-11" : {
    "title" : [ "Family of Ida B. Wells and Ferdinand Barnett" ],
    "creator" : [ "unknown" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "Barnett, Charles Aked, born 1896", "Barnett, Ferdinand Lee, 1852-1936", "Barnett, Albert Graham, born 1886", "Barnett, Hulette", "Barnett, Ferdinand Lee, born 1884", "Duster, Alfreda Barnett, 1904-1983", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "1917" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-002-11" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Family of Ida B. Wells-Barnett, activist, journalist, teacher, and anti-lynching leader, and lawyer Ferdinand Lee Barnett, publisher of The Conservator, the first African American newspaper in Chicago. From left (2nd row): Hulette (wife of Albert Barnett); Herman Kohlsaat; Sergeant Ferdinand Lee, Jr.; Ida B., Jr.; Charles Aked; Albert Graham; (1st row): Hulette (child of Albert and Hulette); Mr. Barnett; Beatrice, Audrey, and Florence (children of Albert and Hulette); Mrs. Wells-Barnett; and Alfreda Marguerita." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-002-11.pdf"
  },
  "ibwells-0008-009-03" : {
    "title" : [ "\"\"Afro-Americans and Africa,\" The A.M.E. Church Review, vol. 9, no. 1 (July 1892)" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Periodicals" ],
    "date" : [ "1892-07" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-009-04.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Article written by Ida B. Wells for the A.M.E. Church Review. Photocopy." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-009-03.pdf"
  },
  "ibwells-0009-004-07" : {
    "title" : [ "Articles Laid in the Cornerstone of the Ida B. Wells Homes" ],
    "creator" : [ "unknown" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ ],
    "date" : [ "1941-06-08" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0009-004-07.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/UND/1.0/" ],
    "description" : [ "Typescript list of Articles Laid in the Cornerstone of the Ida B. Wells Homes, 454 East Pershing Road,Chicago." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0009-004-07.pdf"
  },
  "ibwells-0010-003-22" : {
    "title" : [ "Ida B. Wells at banquet" ],
    "creator" : [ "unknown" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "undated" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-003-22" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Newspaper clipping (photograph copy) of Ida B. Wells-Barnett, activist, journalist, teacher, and anti-lynching leader (right, foreground) pictured at an unidentified event." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-003-22.pdf"
  },
  "ibwells-0010-004-03" : {
    "title" : [ "\"Lynch Law in the United States,\" Birmingham Daily Post, May 17, 1894" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931", "Birmingham Daily Post" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Newspapers" ],
    "date" : [ "1894-05-17" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0010-004-03.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "\"Lynch Law in the United States,\" Birmingham Daily Post, annotated by Ida B. Wells, May 17, 1894. Photocopy" ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-004-03.pdf"
  },
  "ibwells-0010-004-02" : {
    "title" : [ " Editorial, Birmingham Daily Gazette, May 18, 1894" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931", "Birmingham Daily Gazette" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Newspapers" ],
    "date" : [ "1894-05-18" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0010-004-02.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ " Editorial, Birmingham Daily Gazette, annotated by Ida B. Wells, May 18, 1894. Photocopy" ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-004-02.pdf"
  },
  "ibwells-0009-004-06" : {
    "title" : [ "Program for the dedication of the Ida B. Wells Homes" ],
    "creator" : [ "Chicago Housing Authority" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ ],
    "date" : [ "1940-10-27" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0009-004-06.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/UND/1.0/" ],
    "description" : [ "Program for the dedication of the Ida B. Wells Homes." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0009-004-06.pdf"
  },
  "ibwells-0008-009-02" : {
    "title" : [ "\"Editorial,\" New York Age, September 12, 1891" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Newspapers", "Manuscripts" ],
    "date" : [ "1891-09-12" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-009-02.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Handwritten copy of an editorial, \"Senator Bruce,\" published in the September 12, 1891 edition of the New York Age, responding to criticisms of Bruce made by Ida B. Wells in the Memphis Free Speech newspaper. Text also includes notes and a draft letter." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-009-02.pdf"
  },
  "ibwells-0008-010-09" : {
    "title" : [ "\"Idol of her People: Ida B. Wells, the Colored Advocate, Welcomed Home,\" The Daily Inter-Ocean, August 8, 1894" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931", "Daily Inter-Ocean" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Newspapers" ],
    "date" : [ "1894-08-08" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-010-09.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "\"Idol of her People: Ida B. Wells, the Colored Advocate, Welcomed Home,\" The Daily Inter-Ocean, August 8, 1894" ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-010-09.pdf"
  },
  "ibwells-0009-007" : {
    "title" : [ "Ida B. Wells pocket diary, 1930" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Diaries" ],
    "date" : [ "1930" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0009-007.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Ida B. Wells' pocket diary, 1930. Entries begin Christmas Day, 1929, and end May 14, 1930 [entries do not accord with printed date headings], including addresses and record of household expenses." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0009-007.pdf"
  },
  "ibwells-0009-004-04" : {
    "title" : [ "Letter, Alfreda M. Duster to Mr. A.E. Perkins" ],
    "creator" : [ "Duster, Alfreda, 1904-" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ ],
    "date" : [ "1940-10-27" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0009-004-04.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/UND/1.0/" ],
    "description" : [ "Letter from Alfreda M. Duster, daughter of Ida B. Wells, to A.E Perkins, Principal of Daneel Public School in New Orleans, responding to his request for biographical publications about her mother. " ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0009-004-04.pdf"
  },
  "ibwells-0010-003-21" : {
    "title" : [ "Alfreda M. Barnett, circa 1920" ],
    "creator" : [ "W. F. Griffin" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "Duster, Alfreda Barnett, 1904-1983", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "circa 1920" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-003-21" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Alfreda M. Barnett, age 16, daughter of Ida B. Wells-Barnett, activist, journalist, teacher, and anti-lynching leader, and lawyer Ferdinand Lee Barnett, publisher of The Conservator, the first African American newspaper in Chicago." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-003-21.pdf"
  },
  "ibwells-0010-004-01" : {
    "title" : [ "Articles on Ida B. Wells speaking tour in England, 1894" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931", "Daily Inter-Ocean" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Newspapers" ],
    "date" : [ "1894-04" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0010-004-04.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "\"Ida B. Wells Abroad. The Bishop of Manchester on American Lynching,\" The Daily Inter-Ocean, April 28, 1894: 10; pasted on verso: \"Ida B. Wells Abroad. Speaking in Liverpool Against Lynchers of Negroes,\" The Daily Inter-Ocean, April 9, 1894" ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-004-01.pdf"
  },
  "ibwells-0009-004-05" : {
    "title" : [ "Invitation to dedication of the Ida B. Wells Homes" ],
    "creator" : [ "Chicago Housing Authority" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ ],
    "date" : [ "1940-10-27" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0009-004-05.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/UND/1.0/" ],
    "description" : [ "Invitation from Edward J. Kelly, Mayor of Chicago, and the Chicago Housing Authory to the dedication of the Ida B. Wells Homes." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0009-004-05.pdf"
  },
  "ibwells-0009-006" : {
    "title" : [ "Historical Records of the Conventions of 1895-96 of the Colored Women of America." ],
    "creator" : [ "National Federation of Afro-American Women" ],
    "subject" : [ "National Federation of Afro-American Women", "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ ],
    "date" : [ "1902" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0009-006.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "A history of the club movement among the colored women of the United States of America, as contained in the minutes of the conventions, held in Boston, July 29, 30, 31, 1895, and of the National Federation of Afro-American Women, held in Washington, D.C., July 20, 21, 22, 1896. Boston: National Federation of Afro-American Women, 1902. Photocopy." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0009-006.pdf"
  },
  "ibwells-0008-009-01" : {
    "title" : [ " Personal note [from diary?], \"Have just returned from watch meeting...,\" January 1, 1886" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Diaries", "Manuscripts" ],
    "date" : [ "1886-01-01" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-009-01.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Typescript copy of a short text, perhaps from a diary, written by Ida B. Wells shortly after her return from a New Year's Eve watch meeting." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-009-01.pdf"
  },
  "ibwells-0008-010-08" : {
    "title" : [ "\"Against Lynching: Ida B. Wells and her Recent Mission in England,\" The Daily Inter-Ocean, August 4, 1894" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931", "Daily Inter-Ocean" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Newspapers" ],
    "date" : [ "1894-08-04" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-010-08.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "\"Against Lynching: Ida B. Wells and her Recent Mission in England,\" The Daily Inter-Ocean, August 4, 1894. Photocopy" ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-010-08.pdf"
  },
  "ibwells-0010-005" : {
    "title" : [ "The Reason Why the Colored American is Not in the World's Columbian Exposition." ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Pamphlets" ],
    "date" : [ "1893-07" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0010-005.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "The Reason Why the Colored American is Not in the World's Columbian Exposition. Pamphlet. Chicago: privately printed, 1893" ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-005.pdf"
  },
  "ibwells-0010-001-09" : {
    "title" : [ "Ida B. Wells-Barnett with daughters Ida, 13, and Alfreda, 10, September 1914." ],
    "creator" : [ "unknown" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "Barnett, Ida B. Wells, 1901-1988", "Duster, Alfreda Barnett, 1904-1983", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "1914-09" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-001-09" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Daughters of Ida B. Wells-Barnett, activist, journalist, teacher, and anti-lynching leader, and lawyer Ferdinand Lee Barnett, publisher of The Conservator, the first African American newspaper in Chicago. From left: Thirteen-year-old Ida, Jr.; ten-year-old Alfreda; Mrs. Wells-Barnett." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-001-09.pdf"
  },
  "ibwells-0008-009-05" : {
    "title" : [ "Letter, Ida B. Wells to Charles W. Chesnutt," ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers", "Chesnutt, Charles W, (Charles Waddell), 1858-1932" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Letters" ],
    "date" : [ "1893-02-18" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-009-05.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Letter from Ida B. Wells to author and activist Charles W. Chesnutt, inviting him to speak at a dinner of the Equal Rights League. Photocopy" ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-009-05.pdf"
  },
  "ibwells-0009-004-01" : {
    "title" : [ " \"Good Homes, Low Rents\"" ],
    "creator" : [ "Chicago Housing Authority" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ ],
    "date" : [ "undated" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0009-004-01.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/UND/1.0/" ],
    "description" : [ "\"Good Homes, Low Rents,\" brochure and preliminary application for apartments in Ida B. Wells Homes, a public housing project built in 1939 on the South Side of Chicago." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0009-004-01.pdf"
  },
  "ibwells-0008-009-10-11" : {
    "title" : [ "\"The New Year,\" January 1, 1931" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Essays", "Manuscripts" ],
    "date" : [ "1931-01-01" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-009-10-11.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Handwritten and typescript copies of a text written by Ida B. Wells on January 1, 1931, noting African-American political and artistic triumphs in the \"The Old Year,\" 1930." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-009-10-11.pdf"
  },
  "ibwells-0010-004-05" : {
    "title" : [ "\"A Wearied Councillor's Protest,\" May 12, 1894, and reply by Ida B. Wells, \"Lynch Law in the United States,\" Birmingham Daily Post, May 14, 1894" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931", "Birmingham Daily Post" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Newspapers" ],
    "date" : [ "1894-05-14" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0010-004-05.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ " [A City Councillor], \"A Wearied Councillor's Protest,\" May 12, 1894, and reply by Ida B. Wells, \"Lynch Law in the United States,\" Birmingham Daily Post, [annotated by Ida B. Wells], May 14, 1894. Photocopy" ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-004-05.pdf"
  },
  "ibwells-0010-004-04" : {
    "title" : [ "\"Lynch Law in America,\" Birmingham Daily Post, May 17, 1894" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931", "Birmingham Daily Post" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Newspapers" ],
    "date" : [ "1894-05-17" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0010-004-04.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "\"Lynch Law in America,\" Birmingham Daily Post, annotated by Ida B. Wells, May 17, 1894. Photocopy" ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-004-04.pdf"
  },
  "ibwells-0008-009-04" : {
    "title" : [ "Letter, Ida B. Wells to Charles W. Chesnutt, June 4, 1910" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers", "Chesnutt, Charles W, (Charles Waddell), 1858-1932" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Letters" ],
    "date" : [ "1901-06-04" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-009-04.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Letter from Ida B. Wells to author and activist Charles W. Chesnutt, extending an invitation for a series of speaking engagements in Chicago. Typescript with handwritten annotations. Photocopy." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-009-04.pdf"
  },
  "ibwells-0010-001-08" : {
    "title" : [ "Maureen Moss Browning, foster daughter of Ida B. Wells" ],
    "creator" : [ "unknown" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "Browning, Maurine Moss, 1891-1971", "Moss, Thomas Henry, died 1892", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Image" ],
    "format" : [ "Photographic prints" ],
    "date" : [ "undated" ],
    "identifier" : [ "http://pi.lib.uchicago.edu/1001/scrc/md/ibwells-0010-001-08" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Maurine Moss, foster daughter of activist, journalist, and teacher Ida B. Wells-Barnett. Her father Thomas H. Moss, a postman and grocery store owner, was lynched in Memphis, Tennessee, 9 March 1892, an event which compelled Mrs. Wells-Barnett to begin her anti-lynching crusade." ],
    "spatial" : [ "Chicago, Illinois" ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-001-08.pdf"
  },
  "ibwells-0008-009-12" : {
    "title" : [ "Calling card of Mrs. Ida B. Wells-Barnett, undated" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Calling cards" ],
    "date" : [ "undated" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-009-12.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Calling card of Mrs. Ida B. Wells-Barnett, \"National Organizer, Illinois Colored Women,\" inscribed on verso with handwritten reservation form for the Women's Republican League's Whist Party." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-009-12.pdf"
  },
  "ibwells-0008-009-06" : {
    "title" : [ "Letter, Ida B. Wells to Charles W. Chesnutt, May 29, 1915" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers", "Chesnutt, Charles Waddell, 1858-1932" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Letters" ],
    "date" : [ "1915-05-29" ],
    "identifier" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "rights" : [ "http://rightsstatements.org/vocab/InC/1.0/" ],
    "description" : [ "Letter from Ida B. Wells to author and activist Charles Chesnutt, extending an invitation to a dinner planned by the Negro Fellowship League in Chicago. Photocopy." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-009-06.pdf"
  },
  "ibwells-0009-004-02" : {
    "title" : [ "\"Let's Make History!\"" ],
    "creator" : [ "Ida B. Wells Woman's Club" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ ],
    "date" : [ "circa 1938" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0009-004-02.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/UND/1.0/" ],
    "description" : [ "\"\"Let's Make History!\" promotional flyer issued by the Ida B. Wells Woman's Club, to name a new Chicago Housing Authority apartment project after Ida B. Wells." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0009-004-02.pdf"
  },
  "ibwells-0010-004-06" : {
    "title" : [ "\"Editorial notice of Wells' visit to Manchester, England, Manchester Guardian, April 1894" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931", "Manchester Guardian" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Newspapers" ],
    "date" : [ "1894-04" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0010-004-06.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Editorial notice of Well's lecture at Temperance Hall, Ashton, Manchester Guardian, April 1894. Annotated by Ida B. Wells. Photocopy" ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0010-004-06.pdf"
  },
  "ibwells-0009-004-03" : {
    "title" : [ "News release from Chicago Housing Authority" ],
    "creator" : [ "Chicago Housing Authority" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ ],
    "date" : [ "1940-09-03" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0009-004-03.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/UND/1.0/" ],
    "description" : [ "News release from the Chicago Housing Authority warning potential tenants of the new Ida B. Wells Homes of \"racketeers\" posing as agents of the CHA." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0009-004-03.pdf"
  },
  "ibwells-0008-009-07" : {
    "title" : [ "The Alpha Suffrage Record, Chicago: Vol 1, No. 1, March 18, 1914" ],
    "creator" : [ "Alpha Suffrage Club" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Newsletters" ],
    "date" : [ "1914-03-18" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-009-07.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "First issues of The Alpha Suffrage Record, published by the Alpha Suffrage Club, the first Black women's suffrage club in Illinois, co-founded by Ida B. Wells." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-009-07.pdf"
  },
  "ibwells-0008-009-13" : {
    "title" : [ "Campaign card supporting Mrs. Ida B. Wells-Barnett, candidate for Delegate to Republican National Convention, Kansas City, MO, June 1928" ],
    "creator" : [ "Wells-Barnett, Ida B., 1862-1931" ],
    "subject" : [ "Wells-Barnett, Ida B., 1862-1931", "African American women civil rights workers" ],
    "isPartOf" : [ "Ida B. Wells. Papers" ],
    "type" : [ "Text" ],
    "format" : [ "Business cards" ],
    "date" : [ "1886" ],
    "identifier" : [ "https://www.lib.uchicago.edu/ead/pdf/ibwells-0008-009-13.pdf" ],
    "rights" : [ "http://rightsstatements.org/vocab/NoC-US/1.0/" ],
    "description" : [ "Campaign card of Ida B. Wells-Barnett, activist, journalist, teacher, and anti-lynching leader. Support for her candidacy is requested as a delegate to the Republican National Convention in Kansas City, Missouri, June 1928." ],
    "spatial" : [ ],
    "publisher" : [ "University of Chicago Library, Special Collections Research Center" ],
    "language" : [ ],
    "href" : "https://dpla-bws.s3-website-us-east-1.amazonaws.com/IBW-20200818/ibwells-0008-009-13.pdf"
  }
}