module.exports = {
  "successfully loads homepage": {
    "Banner Title": "1820-1859 | Black Women's Suffrage Timeline | DPLA"
  },
  "checks that hero banner is visible": {
    "1": "<section class=\"PageBanner_banner__1ayRR\"\n  data-cy=\"banner\">\n  <div class=\"PageBanner_banner_left__div__2zit7\">\n    <h6>TIMELINE</h6>\n    <p>Marching toward progress: the journey to Black women’s suffrage.</p>\n  </div>\n  <div>\n    <div><img src=\"/static/graphic/timeline-page/timeline-graphic-hero.png\"\n        alt=\"\"></div>\n  </div>\n</section>",
    "2": "<p>Marching toward progress: the journey to Black women’s suffrage.</p>"
  },
  "__version": "5.1.0",
  "checks that primary source set links lead to primary source set": {
    "1": "<a href=\"https://dp.la/primary-source-sets/the-american-abolitionist-movement\"\n  target=\"_blank\">\n  <div class=\"CollectionsPage_pss__tile__2QUmw\"><img\n      src=\"/static/image/primary-source-sets/primary-image-american-abolitionist-movement.jpg\"\n      alt=\"The American Abolitionist Movement\">\n    <h2>The American Abolitionist Movement</h2>\n    <h3>Expansion and Reform (1801-1861)</h3>\n  </div>\n</a>",
    "2": "<a href=\"https://dp.la/primary-source-sets/the-american-abolitionist-movement\"\n  target=\"_blank\">\n  <div class=\"CollectionsPage_pss__tile__2QUmw\"><img\n      src=\"/static/image/primary-source-sets/primary-image-american-abolitionist-movement.jpg\"\n      alt=\"The American Abolitionist Movement\">\n    <h2>The American Abolitionist Movement</h2>\n    <h3>Expansion and Reform (1801-1861)</h3>\n  </div>\n</a>",
    "3": "<a href=\"https://dp.la/primary-source-sets/ida-b-wells-and-anti-lynching-activism\"\n  target=\"_blank\">\n  <div class=\"CollectionsPage_pss__tile__2QUmw\"><img\n      src=\"/static/image/primary-source-sets/primary-ibw-anti-lynching.jpg\"\n      alt=\"Ida B. Wells and Anti-Lynching Activism\">\n    <h2>Ida B. Wells and Anti-Lynching Activism</h2>\n    <h3>The Emergence of Modern America (1890-1930)</h3>\n  </div>\n</a>",
    "4": "<a href=\"https://dp.la/primary-source-sets/ida-b-wells-and-anti-lynching-activism\"\n  target=\"_blank\">\n  <div class=\"CollectionsPage_pss__tile__2QUmw\"><img\n      src=\"/static/image/primary-source-sets/primary-ibw-anti-lynching.jpg\"\n      alt=\"Ida B. Wells and Anti-Lynching Activism\">\n    <h2>Ida B. Wells and Anti-Lynching Activism</h2>\n    <h3>The Emergence of Modern America (1890-1930)</h3>\n  </div>\n</a>",
    "5": "<a href=\"https://dp.la/primary-source-sets/women-s-suffrage-the-campaign-for-the-nineteenth-amendment\"\n  target=\"_blank\">\n  <div class=\"CollectionsPage_pss__tile__2QUmw\"><img\n      src=\"/static/image/primary-source-sets/primary-womens-suffrage.jpg\"\n      alt=\"Women's Suffrage: Campaign for the Nineteenth Amendment\">\n    <h2>Women's Suffrage: Campaign for the Nineteenth Amendment</h2>\n    <h3>The Emergence of Modern America (1890-1930)</h3>\n  </div>\n</a>",
    "6": "<a href=\"https://dp.la/primary-source-sets/women-s-suffrage-the-campaign-for-the-nineteenth-amendment\"\n  target=\"_blank\">\n  <div class=\"CollectionsPage_pss__tile__2QUmw\"><img\n      src=\"/static/image/primary-source-sets/primary-womens-suffrage.jpg\"\n      alt=\"Women's Suffrage: Campaign for the Nineteenth Amendment\">\n    <h2>Women's Suffrage: Campaign for the Nineteenth Amendment</h2>\n    <h3>The Emergence of Modern America (1890-1930)</h3>\n  </div>\n</a>",
    "7": "<a href=\"https://dp.la/primary-source-sets/fannie-lou-hamer-and-the-civil-rights-movement-in-rural-mississippi\"\n  target=\"_blank\"><img\n    src=\"/static/image/primary-source-sets/primary-flh-civil-rights-movement.jpg\"\n    alt=\"Fannie Lou Hamer and the Civil Rights Movement in Mississippi\">\n  <h2>Fannie Lou Hamer and the Civil Rights Movement in Mississippi</h2>\n  <h3>Postwar United States (1945 to early 1970s)</h3>\n</a>",
    "8": "<a href=\"https://dp.la/primary-source-sets/fannie-lou-hamer-and-the-civil-rights-movement-in-rural-mississippi\"\n  target=\"_blank\"><img\n    src=\"/static/image/primary-source-sets/primary-flh-civil-rights-movement.jpg\"\n    alt=\"Fannie Lou Hamer and the Civil Rights Movement in Mississippi\">\n  <h2>Fannie Lou Hamer and the Civil Rights Movement in Mississippi</h2>\n  <h3>Postwar United States (1945 to early 1970s)</h3>\n</a>",
    "9": "<a href=\"https://dp.la/primary-source-sets/the-black-power-movement\"\n  target=\"_blank\"><img\n    src=\"/static/image/primary-source-sets/primary-black-power-movement.jpg\"\n    alt=\"The Black Power Movement\">\n  <h2>The Black Power Movement</h2>\n  <h3>Postwar United States (1945 to early 1970s)</h3>\n</a>",
    "10": "<a href=\"https://dp.la/primary-source-sets/the-black-power-movement\"\n  target=\"_blank\"><img\n    src=\"/static/image/primary-source-sets/primary-black-power-movement.jpg\"\n    alt=\"The Black Power Movement\">\n  <h2>The Black Power Movement</h2>\n  <h3>Postwar United States (1945 to early 1970s)</h3>\n</a>",
    "11": "<a href=\"https://dp.la/primary-source-sets/the-equal-rights-amendment\"\n  target=\"_blank\"><img\n    src=\"/static/image/primary-source-sets/primary-equal-rights-amendment.jpg\"\n    alt=\"The Equal Rights Amendment\">\n  <h2>The Equal Rights Amendment</h2>\n  <h3>Contemporary United States (1968 to the present)</h3>\n</a>",
    "12": "<a href=\"https://dp.la/primary-source-sets/the-equal-rights-amendment\"\n  target=\"_blank\"><img\n    src=\"/static/image/primary-source-sets/primary-equal-rights-amendment.jpg\"\n    alt=\"The Equal Rights Amendment\">\n  <h2>The Equal Rights Amendment</h2>\n  <h3>Contemporary United States (1968 to the present)</h3>\n</a>"
  }
}
